source "https://rubygems.org"

ruby "2.5.3"

gem "bourbon"
gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-autoprefixer"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-sprockets"
gem "middleman-syntax"
gem "neat", "3.0.1"
gem "rake"
gem "redcarpet"
gem "sassc"
gem "scss_lint", require: false
gem "slim"
gem "slugify"
