source "https://rubygems.org"

ruby "2.4.1"

gem "bourbon", "~> 5.1"
gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-autoprefixer"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-sprockets"
gem "middleman-syntax"
gem "neat", "3.0.0"
gem "rake"
gem "redcarpet"
gem "sassc"
gem "scss_lint", require: false
gem "slim"
gem "slugify"
