[build]
  publish = "build"
  command = "bundle exec middleman build --verbose"

[[redirects]]
  from = "/docs"
  to = "/docs/latest"
  status = 301

[[redirects]]
  from = "https://neat.netlify.com/*"
  to = "https://neat.bourbon.io/:splat"
  status = 301
  force = true
